const loginPageRoute = "/login";
const singupPageRoute = "/signup";
const homePageRoute = '/home';
const handGestureRoute = '/hand_gesture/';
const profilePageRoute = '/profile';
const emotionsPageRoute = '/emotions';
const categoryPageRoute = '/emotions/category';
const learnAplhabetPageRoute = handGestureRoute + 'learn_alphabet';
const learnWordPageRoute = handGestureRoute + 'learn_word';
